name: technopark-docker-compose
services:
  app:
    image: techno-park-site
    expose:
      - '5000'
    environment:
      - VIRTUAL_HOST=sdutechnopark.kz
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=sdutechnopark.kz
      - LETSENCRYPiT_EMAIL=qaraqatalmasova@gmail.com
    networks:
      production: {}

networks:
  production:
    external: true
    name: production